# Generated by Django 5.2.4 on 2025-07-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.CharField(max_length=10)),
                ('matiere', models.CharField(max_length=100)),
                ('chapitre', models.CharField(max_length=255)),
                ('periode', models.CharField(max_length=100)),
                ('num_chapitre', models.PositiveIntegerField()),
            ],
        ),
    ]
